name: Run PyAutoGUI Bot + Docker Parallel

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    # - cron: '2,32,47 * * * *'
    - cron: '*/30 * * * *'
    

jobs:
  run-pyautogui:
    name: Run PyAutoGUI (Windows)
    runs-on: windows-latest
    timeout-minutes: 13
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false

    steps:
      - name: ‚¨áÔ∏è Checkout Repo
        uses: actions/checkout@v4

      - name: üêç Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: üì¶ Install dependencies
        run: |
          pip install -r requirements.txt

      - name: ‚ñ∂Ô∏è Run bot script (PyAutoGUI)
        run: python main.py

      - name: ‚ñ∂Ô∏è Run bot script 2 (PyAutoGUI)
        run: python main.py

  run-docker:
    name: Run Docker Containers (Ubuntu)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false

    steps:
      - name: üê≥ Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: üê≥ Pull Docker Image
        run: docker pull nduythanh1/selenium-videozz-multiprocess

      - name: ‚ñ∂Ô∏è Run 3 Docker Containers in Parallel
        run: |
          docker run -d --name container1-${{ matrix.job_id }} -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-videozz-multiprocess
          docker run -d --name container2-${{ matrix.job_id }} -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-videozz-multiprocess
          docker run -d --name container3-${{ matrix.job_id }} -e JOB_ID=${{ matrix.job_id }} nduythanh1/selenium-videozz-multiprocess
          
          # ƒê·ª£i c·∫£ 3 container ho√†n t·∫•t (song song)
          docker wait container1-${{ matrix.job_id }} &
          docker wait container2-${{ matrix.job_id }} &
          docker wait container3-${{ matrix.job_id }} &
          wait
